# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ipCalculator(object):
    def setupUi(self, ipCalculator):
        ipCalculator.setObjectName("ipCalculator")
        ipCalculator.resize(837, 453)
        self.centralwidget = QtWidgets.QWidget(ipCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        ipCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ipCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 26))
        self.menubar.setObjectName("menubar")
        ipCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ipCalculator)
        self.statusbar.setObjectName("statusbar")
        ipCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(ipCalculator)
        QtCore.QMetaObject.connectSlotsByName(ipCalculator)

    def retranslateUi(self, ipCalculator):
        _translate = QtCore.QCoreApplication.translate
        ipCalculator.setWindowTitle(_translate("ipCalculator", "MainWindow"))
        self.label.setText(_translate("ipCalculator", "IPv4 адрес"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ipCalculator = QtWidgets.QMainWindow()
    ui = Ui_ipCalculator()
    ui.setupUi(ipCalculator)
    ipCalculator.show()
    sys.exit(app.exec_())
